run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - typecheck
    - errcheck
    - staticcheck
    - gosimple
    - unused

issues:
  exclude-use-default: false
